#version 430 core

uniform int numParticles;

layout (local_size_x = WORKGROUP_SIZE) in;

layout(std430, binding = 5) buffer CellIndices {
    uint cellIndices[];
};

layout(std430, binding = 6) buffer CellOffsets {
    uint cellOffsets[];
};

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= numParticles) return;

    uint cellIndex = cellIndices[id];

    atomicMin(cellOffsets[cellIndex], id);
}
